name: Spotify to MEGA

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '*/30 * * * *' # Adjust this to your preferred time (UTC)

jobs:
  sync-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Spotify Archive
        uses: actions/cache@v3
        with:
          path: spotify_playlist.txt
          key: spotify-archive-21yqmD9oVk0ah2n6Lob2zu
          restore-keys: spotify-archive-

      - name: Setup Package
        run: |
          sudo apt-get install -y wget curl
          sudo -v ; curl https://rclone.org/install.sh | sudo bash -s beta
          pip install spotdl
          spotdl --download-ffmpeg
          wget https://gist.githubusercontent.com/ZYGYU/b1d029a30883ba24a8665c151313e464/raw/b9f431a130f8aa864e72e6a8cbe8f54fed65c777/cookies.txt

      - name: Download Rclone Config
        run: |
          wget -O rclone.conf https://gist.githubusercontent.com/ZYGYU/95d006b7e760c724c3671288333d50f3/raw/c5602bc6cbf806548547bada3a8a4be96b672214/rclone.conf

      - name: Run Spotify to MEGA Script
        run: |
          # Variables
          SPOTIFY_ARCHIVE="spotify_playlist.txt"
          SPOTIFY_PLAYLIST_URL="https://open.spotify.com/playlist/21yqmD9oVk0ah2n6Lob2zu"
          MUSIC_DIR="$HOME/music"
          RCLONE_REMOTE="mg:music"

          # Ensure directories exist
          mkdir -p "$MUSIC_DIR"

          # Download Spotify Playlist
          spotdl download "$SPOTIFY_PLAYLIST_URL" \
            --bitrate 128k \
            --cookie-file cookies.txt \
            --archive "$SPOTIFY_ARCHIVE" \
            --output "$MUSIC_DIR/{artists} - {title}.{output-ext}"

          # Upload to MEGA using Rclone
          rclone copy "$MUSIC_DIR" "$RCLONE_REMOTE" \
            --transfers 2 \
            --progress --ignore-existing \
            --config rclone.conf
