name: Spotify to MEGA

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Package
        run: |
          sudo apt-get install -y wget curl
          sudo -v ; curl https://rclone.org/install.sh | sudo bash -s beta
          pip install spotdl
          spotdl --download-ffmpeg

      - name: Load Rclone Config from Secret
        run: |
          echo "$RCLONE_CONF_BASE64" | base64 --decode > rclone.conf
        env:
          RCLONE_CONF_BASE64: ${{ secrets.RCLONE_CONF_BASE64 }}

      - name: Load Cookies File from Secret
        run: |
          echo "$COOKIES_TXT_BASE64" | base64 --decode > cookies.txt
        env:
          COOKIES_TXT_BASE64: ${{ secrets.COOKIES_TXT_BASE64 }}

      - name: Run Spotify to MEGA Script
        run: |
          # Variables
          SPOTIFY_PLAYLIST_URL="https://open.spotify.com/playlist/21yqmD9oVk0ah2n6Lob2zu"
          MUSIC_DIR="$HOME/music"
          RCLONE_REMOTE="mg:music"
          ARCHIVE_FILE="$GITHUB_WORKSPACE/archive.txt"
          TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"

          # Ensure directories exist
          mkdir -p "$MUSIC_DIR"

          # Download Spotify Playlist
          spotdl download "$SPOTIFY_PLAYLIST_URL" \
            --bitrate 128k \
            --archive "$ARCHIVE_FILE" \
            --cookie-file cookies.txt \
            --output "$MUSIC_DIR/{artists} - {title}.{output-ext}"

          # Upload to MEGA using Rclone
          rclone copy "$MUSIC_DIR" "$RCLONE_REMOTE" \
            --transfers 2 \
            --progress --ignore-existing \
            --config rclone.conf

          # Upload audio files to Telegram
          for file in "$MUSIC_DIR"/*; do
              if [ -f "$file" ]; then
                  BASENAME=$(basename "$file")
  
                  # Check if file is already archived
                  if grep -Fxq "$BASENAME" "$ARCHIVE_FILE"; then
                      echo "File $BASENAME already uploaded, skipping."
                  else
                      echo "Uploading $BASENAME to Telegram..."
                      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendAudio" \
                        -F "chat_id=$TELEGRAM_CHAT_ID" \
                        -F "audio=@$file"
                      
                      if [ $? -eq 0 ]; then
                          echo "$BASENAME" >> "$ARCHIVE_FILE"
                          echo "Successfully uploaded $BASENAME."
                      else
                          echo "Failed to upload $BASENAME."
                      fi
                  fi
              else
                  echo "Invalid file: $file"
              fi
          done
